#!/usr/bin/env bash
# Configures Nginx as nginx user on port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo systemctl stop apache2
sudo systemctl start nginx

